# Generated by Django 4.2.7 on 2025-05-21 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("computadores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anomalia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("data_registo", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("EM_RESOLUCAO", "Em Resolução"),
                            ("RESOLVIDO", "Resolvido"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                    ),
                ),
                (
                    "computador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalias",
                        to="computadores.computador",
                    ),
                ),
                (
                    "reportado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
