# Generated by Django 4.2.7 on 2025-05-21 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("salas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Computador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_identificacao", models.CharField(max_length=20)),
                ("marca", models.CharField(max_length=50)),
                ("modelo", models.CharField(max_length=50)),
                ("data_aquisicao", models.DateField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "sala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="computadores",
                        to="salas.sala",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Computadores",
            },
        ),
    ]
